// scripts/copy-abis.js
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const artifacts = {
  core: path.join(__dirname, '../artifacts/contracts/DeRedditCore.sol/DeRedditCore.json'),
  escrow: path.join(__dirname, '../artifacts/contracts/DeRedditEscrow.sol/DeRedditEscrow.json'),
  iCore: path.join(__dirname, '../artifacts/contracts/DeRedditEscrow.sol/IDeRedditCore.json'),
};

const frontendPath = path.join(__dirname, '../frontend/src/lib/abi.ts');
const backendPath = path.join(__dirname, '../backend/src/abis.ts');

function loadAbi(filePath) {
  if (!fs.existsSync(filePath)) {
    console.error(` Error: Artifact not found at ${filePath}`);
    console.error(' Please run "npx hardhat compile" before running this script.\n');
    process.exit(1);
  }
  const fileContent = fs.readFileSync(filePath, 'utf8');
  return JSON.parse(fileContent).abi;
}

try {
  const coreAbi = loadAbi(artifacts.core);
  const escrowAbi = loadAbi(artifacts.escrow);
  const iCoreAbi = loadAbi(artifacts.iCore);

  const frontendContent = `// Auto-generated by scripts/copy-abis.js - DO NOT EDIT MANUALLY

export const CORE_ABI = ${JSON.stringify(coreAbi, null, 2)} as const;

export const ESCROW_ABI = ${JSON.stringify(escrowAbi, null, 2)} as const;

export const I_CORE_ABI = ${JSON.stringify(iCoreAbi, null, 2)} as const;
`;

  fs.writeFileSync(frontendPath, frontendContent);
  console.log(' Updated frontend/src/lib/abi.ts');

  const backendContent = `// Auto-generated by scripts/copy-abis.js - DO NOT EDIT MANUALLY

// PostType enum mapping - mirrors Solidity enum order (checked against DeRedditTypes.sol)
export const POST_TYPE: Record<number, string> = {
  0: "Standard",
  1: "TimeCapsule",
  2: "Poll",
  3: "Crowdfund",
};

export const CORE_ABI = ${JSON.stringify(coreAbi, null, 2)} as const;

export const ESCROW_ABI = ${JSON.stringify(escrowAbi, null, 2)} as const;

export const I_CORE_ABI = ${JSON.stringify(iCoreAbi, null, 2)} as const;
`;

  fs.writeFileSync(backendPath, backendContent);
  console.log(' Updated backend/src/abis.ts');

  console.log('\n ABI synchronization completed successfully!');
} catch (error) {
  console.error(' Failed to synchronize ABIs:', error);
  process.exit(1);
}